deploy: c4bf16c26fce9dbf0ccb11adc0215661c3117a7e

diff --git a/healthcheck b/healthcheck
--- a/healthcheck
+++ b/healthcheck
@@ -209,6 +209,18 @@ warningCount=0
     else
       echo "✅ The localhost:4230/health is okay"
     fi
+  else
+    echo "⚠️ WARNING: Your setup seems to be custom, e.g. running quickly with Docker or Lightning CLI, in any of this cases without Systemd service wrapper, etc. Be aware the tools provided via get.fleek.network are meant for recommeded setups via docs or tools."
+    echo
+
+    if ! curl -s -w "\n" localhost:4230/health | grep -iq 'running and staked'; then
+      echo "⚠️ WARNING: Failed to get a response from localhost:4230/health. The node seems to be offline (not running), if you are participating in testnet, then read the instructions in https://docs.fleek.network/docs/node/testnet-onboarding, to run successfully!"
+
+      ((warningCount++))
+      ((healthIssueCount++))
+    else
+      echo "✅ The localhost:4230/health is okay"
+    fi
   fi
 
   echo
