refactor: 💡 acme challenge health check

diff --git a/install_native b/install_native
--- a/install_native
+++ b/install_native
@@ -32,6 +32,7 @@ defaultNginxSitesAvailablePath="/etc/nginx/sites-available"
 defaultNginxSitesEnabledPath="/etc/nginx/sites-enabled"
 defaultUrsaNginxHttpConfFilename="ursa-http.conf"
 defaultUrsaNginxHttpsConfFilename="ursa-https.conf"
+defaultACMEChallengeMsgPlaceholder="_domain_ ACME Challenge directory is healthy!"
 
 # App state
 selectedUrsaPath="$defaultUrsaPath"
@@ -429,6 +430,9 @@ echo "
   }
 " > "$selectedNginxSitesEnabledPath/$defaultUrsaNginxHttpsConfFilename"
 
+printf "🤖 Create ACME Challenge directory health check placeholder\n"
+echo "${defaultACMEChallengeMsgPlaceholder/_domain_/$selectedDomainName}" >> "/var/www/$selectedDomainName/.well-known/acme-challenge/healthcheck"
+
 printf "🤖 Enable Nginx HTTP config for now, HTTPS will be enabled after the SSL/TLS setup from Let's Encrypt\n"
 if [[ -f "$selectedNginxSitesEnabledPath/$defaultUrsaNginxHttpConfFilename" ]]; then
   rm "$selectedNginxSitesEnabledPath/$defaultUrsaNginxHttpConfFilename"
@@ -474,7 +478,18 @@ else
   fi
 fi
 
+printf "🚑 ACME Challenge health-check\n"
+if ! curl -s "http://$selectedDomainName/.well-known/acme-challenge/healthcheck" | grep -q "${defaultACMEChallengeMsgPlaceholder/_domain_/$selectedDomainName}"; then
+  printf "💩 Uh-oh! The ACME Challenge health-check failed for some reason, make sure you don't have any firewall or apps blocking port 80 and 443...\n"
+fi
+
 initCertbot "$selectedDomainName" "$selectedEmailAddress"
+
+printf "🤖 Enable Nginx HTTPS\n"
+if [[ -f "$selectedNginxSitesEnabledPath/$defaultUrsaNginxHttpsConfFilename" ]]; then
+  rm "$selectedNginxSitesEnabledPath/$defaultUrsaNginxHttpsConfFilename"
+fi
+sudo ln -s "$selectedNginxSitesAvailablePath/$defaultUrsaNginxHttpsConfFilename" "$selectedNginxSitesEnabledPath/$defaultUrsaNginxHttpsConfFilename"
 
 printf "🤖 Nginx reload\n"
 service nginx reload
