chore: 🤖 remove symlink

diff --git a/install b/install
--- a/install
+++ b/install
@@ -325,6 +325,12 @@ isOSSupported
 
   printf "🤖 Symlink the %s CLI binary to /usr/local/bin. By default rustup should've set the .cargo/bin into your system PATH, in any case we'll attempt to symlink to ensure %s is available globally\n" "$defaultName" "$defaultDiscordUrl"
   if [[ -f "$HOME/.cargo/bin/$defaultName" ]]; then
+    if [[ -L "/usr/local/bin/$defaultCLIAlias" ]]; then
+      if ! rm "/usr/local/bin/$defaultCLIAlias"; then
+        printf "👹 Oops! Failed to remove simbolic link %s \n" "/usr/local/bin/$defaultCLIAlias"
+      fi
+    fi
+
     if ! ln -s "$HOME/.cargo/bin/$defaultName" /usr/local/bin/$defaultCLIAlias; then
       printf "👹 Oops! Failed to symlink %s to /usr/local/bin/%s\n" "$HOME/.cargo/bin/$defaultName" "$defaultName"
       echo
