refactor: 💡 launch network node script

diff --git a/install_native b/install_native
--- a/install_native
+++ b/install_native
@@ -36,6 +36,11 @@ defaultACMEChallengeMsgPlaceholder="_domain_ ACME Challenge directory is healthy
 defaultLetsEncryptOptionsSSLNginxConf="/etc/letsencrypt/options-ssl-nginx.conf"
 defaultLetsEncryptSSLDHParams="/etc/letsencrypt/ssl-dhparams.pem"
 defaultUrsaLogPath="/var/log/ursa"
+defaultUrsaDiagnosticFilename="diagnostic.log"
+defaultUrsaOutputFilename="output.log"
+defaultUrsaDiagnosticLogAbsPath="$defaultUrsaLogPath/$defaultUrsaDiagnosticFilename"
+defaultUrsaOutputLogAbsPath="$defaultUrsaLogPath/$defaultUrsaOutputFilename"
+defaultUrsaStartHelperFilename="start_node"
 
 # App state
 selectedUrsaPath="$defaultUrsaPath"
@@ -297,7 +302,7 @@ done
 echo
 
 printf "Let's Encrypt provides SSL/TLS Certificates for securing the communications. A valid email address is required by the Let's Encrypt organisation (Fleek Network is not affiliated and does NOT store the email address).\n"
-printf -v prompt "What's your email address?\n"
+printf -v prompt "What's your email address?"
 while read -rp "$prompt"$'\n> ' answer; do
   if confirmEmailAddress "$answer"; then
     selectedEmailAddress="$answer"
@@ -310,7 +315,7 @@ done
 echo
 
 printf "🤖 The Ursa source-code is going to be stored in the recommended path %s (otherwise, type \"n\" to modify path)\n" "$defaultUrsaPath"
-printf -v prompt "Should we proceed and install to path %s? (yes/no)\n" "$defaultUrsaPath"
+printf -v prompt "Should we proceed and install to path %s? (yes/no)" "$defaultUrsaPath"
 while read -r -p "$prompt"$'\n> ' answer; do
   if [[ "$answer" == [nN] || "$answer" == [nN][oO] ]]; then
     printf -v prompt "\n🙋‍♀️ What path should we clone the Ursa source-code to?\n"
@@ -731,8 +736,9 @@ if ! mkdir -p "$defaultUrsaLogPath"; then
   printf "💩 Uh-oh! Failed to create the Ursa system log dir %s for some reason...\n" "$defaultUrsaLogPath"
 fi
 
-ursa 2> "$defaultUrsaLogPath/diagnostic.log" 1> "$defaultUrsaLogPath/output.log" &
+ursa 2> "$defaultUrsaDiagnosticLogAbsPath" 1> "$defaultUrsaOutputLogAbsPath" &
 
+printf "🚑 Health check %s via HTTPS /ping endpoint\n" "$selectedDomainName"
 if ! curl -s https://$selectedDomainName/ping | grep -q pong; then
   printf "👹 Oh no! Failed to health-check the domain %s\n" "$selectedDomainName"
   echo
@@ -740,3 +746,113 @@ if ! curl -s https://$selectedDomainName/ping | grep -q pong; then
 
   exit 1
 fi
+
+printf "✅ Health checked!\n"
+
+cat << "EOF" > "$selectedUrsaPath/$defaultUrsaStartHelperFilename"
+#!/bin/bash
+
+cat << "URSA_START_SCRIPT"
+          _..._
+        .'     '.     _
+      /    .-""-\   _/ \
+    .-|   /:.   |  |   |
+    |  \  |:.   /.-'-./
+    | .-'-;:__.'    =/
+    .'=  *=|URSA _.='
+    /   _.  |    ;
+    ;-.-'|    \   |
+  /   | \    _\  _\
+  \__/'._;.  ==' ==\
+          \    \   |
+          /    /   /
+          /-._/-._/
+          \   `\  \
+            `-._/._/
+URSA_START_SCRIPT
+
+echo
+echo "⭐️ Ursa, a Decentralized Content Delivery Network (DCDN) ⭐️"
+echo
+echo "★★★★★★★★★ 🌍 Website https://fleek.network"
+echo "★★★★★★★★★ 📚 Documentation https://docs.fleek.network"
+echo "★★★★★★★★★ 💾 Git repository https://github.com/fleek-network/ursa"
+echo "★★★★★★★★★ 🤖 Discord https://discord.gg/fleekxyz"
+echo "★★★★★★★★★ 🐤 Twitter https://twitter.com/fleek_net"
+echo "★★★★★★★★★ 🎨 Ascii art by https://www.asciiart.eu"
+echo
+
+if ! ursa 2> _defaultUrsaDiagnosticLogAbsPath_ 1> _defaultUrsaOutputLogAbsPath_ &; then
+  echo "👹 Oops! Failed to launch Network Node..."
+
+  exit 1
+fi
+
+echo
+echo "🌈 The Fleek Network Node is running!"
+echo
+echo "You can watch the Node output by running the command:"
+echo "tail -f _defaultUrsaOutputLogAbsPath_"
+echo
+echo "For diagnostics run the command:"
+echo "tail -f _defaultUrsaDiagnosticLogAbsPath_"
+echo
+echo "Since the Node was started in the background, you can find the job number by:"
+echo "jobs -f"
+echo
+echo "Bring it to the foreground by:"
+echo "fg %<NUMBER>"
+echo
+echo "Here's an example:"
+echo "fg %1"
+echo
+echo "You can stop Ursa by:"
+echo "pkill -9 <PID or NAME>"
+echo
+echo "Here's an example:"
+echo "pkill -9 ursa"
+echo
+echo "Check our documentation site to learn more!"
+echo
+echo "Launch the Network Node by running:"
+echo "./_selectedUrsaPath_/_defaultUrsaStartHelperFilename_"
+echo
+EOF
+
+chmod +x "$selectedUrsaPath/$defaultUrsaStartHelperFilename"
+
+sed -i "s|_defaultUrsaDiagnosticLogAbsPath_|$defaultUrsaDiagnosticLogAbsPath}|g" "$selectedUrsaPath/$defaultUrsaStartHelperFilename"
+sed -i "s|_defaultUrsaOutputLogAbsPath_|$defaultUrsaOutputLogAbsPath|g" "$selectedUrsaPath/$defaultUrsaStartHelperFilename"
+sed -i "s|_selectedUrsaPath_|$selectedUrsaPath|g" "$selectedUrsaPath/$defaultUrsaStartHelperFilename"
+sed -i "s|_defaultUrsaStartHelperFilename_|$defaultUrsaStartHelperFilename|g" "$selectedUrsaPath/$defaultUrsaStartHelperFilename"
+
+echo
+echo "🌈 The Fleek Network Node is running!"
+echo
+echo "You can watch the Node output by running the command:"
+echo "tail -f $defaultUrsaOutputLogAbsPath"
+echo
+echo "For diagnostics run the command:"
+echo "tail -f $defaultUrsaDiagnosticLogAbsPath"
+echo
+echo "Since the Node was started in the background, you can find the job number by:"
+echo "jobs -f"
+echo
+echo "Bring it to the foreground by:"
+echo "fg %<NUMBER>"
+echo
+echo "Here's an example:"
+echo "fg %1"
+echo
+echo "You can stop Ursa by:"
+echo "pkill -9 <PID or NAME>"
+echo
+echo "Here's an example:"
+echo "pkill -9 ursa"
+echo
+echo "Launch the Network Node by running the helper script in:"
+echo "$selectedUrsaPath/$defaultUrsaStartHelperFilename"
+echo
+echo "Here's an example, change directory to $selectedUrsaPath and run:"
+echo "./$defaultUrsaStartHelperFilename"
+echo
