deploy: 3acdbfd8556c55bd9c089e4f81326fb65da434e6

diff --git a/install_ursa_proxy b/install_ursa_proxy
--- a/install_ursa_proxy
+++ b/install_ursa_proxy
@@ -99,6 +99,7 @@ isOSSupported() {
   fi
 }
 
+introAscii() {
 cat << "URSA_START_SCRIPT"
 
           |
@@ -124,6 +125,11 @@ echo "★★★★★★★★★ 🤖 Discord https://discord.gg/fleekxyz"
 echo "★★★★★★★★★ 🐤 Twitter https://twitter.com/fleek_net"
 echo "★★★★★★★★★ 🎨 Ascii art by https://www.asciiart.eu"
 echo
+}
+
+if [[ -z ${SKIP_INTRO+x} ]]; then
+  introAscii
+fi
 
 printf "🤖 Check if operating system is supported\n"
 isOSSupported
@@ -134,23 +140,22 @@ echo
 
   # Defaults
   defaultUrsaPath="$HOME/fleek-network/ursa"
-  defaultUrsaLogPath="/var/log/ursa-proxy"
-  defaultUrsaDiagnosticFilename="diagnostic.log"
-  defaultUrsaOutputFilename="output.log"
+  defaultUrsaProxyLogPath="/var/log/ursa-proxy"
+  defaultUrsaProxyDiagnosticFilename="diagnostic.log"
+  defaultUrsaProxyOutputFilename="output.log"
   defaultUrsaProxySystemdServiceName="ursa-proxy"
-  defaultUrsaSystemdServicePath="/etc/systemd/system/$defaultUrsaProxySystemdServiceName.service"
+  defaultUrsaProxySystemdServicePath="/etc/systemd/system/$defaultUrsaProxySystemdServiceName.service"
   defaultExecCargoProxyCmd="ursa-proxy daemon"
   # TODO: Disabled as ursa-proxy has no output at time of writing
-  defaultUrsaDiagnosticLogAbsPath="$defaultUrsaLogPath/$defaultUrsaDiagnosticFilename"
-  defaultUrsaOutputLogAbsPath="$defaultUrsaLogPath/$defaultUrsaOutputFilename"
-  defaultCargoBinUrsaProxyPath="$HOME/.cargo/bin/$defaultUrsaProxySystemdServiceName"
+  defaultUrsaProxyDiagnosticLogAbsPath="$defaultUrsaProxyLogPath/$defaultUrsaProxyDiagnosticFilename"
+  defaultUrsaProxyOutputLogAbsPath="$defaultUrsaProxyLogPath/$defaultUrsaProxyOutputFilename"
 
   # User data
   selectedUrsaPath=""
 
-  if [[ -f "$defaultUrsaSystemdServicePath" ]]; then
+  if [[ -f "$defaultUrsaProxySystemdServicePath" ]]; then
     # Obs: the extra white space between ⚠️ and warning is for alignment
-    while read -rp "⚠️  Warning! A service of name ursa-proxy has been found at $defaultUrsaSystemdServicePath, the ursa-proxy installer script may override any custom settings if you proceed. Would you like to ignore this warning and proceed? (yes/no)" answer; do
+    while read -rp "⚠️  Warning! A service of name ursa-proxy has been found at $defaultUrsaProxySystemdServicePath, the ursa-proxy installer script may override any custom settings if you proceed. Would you like to ignore this warning and proceed? (yes/no)" answer; do
       if [[ $answer == [nN] || $answer == [nN][oO] ]]; then
         echo "🦖 The ursa-proxy install and setup script has terminated."
 
@@ -161,23 +166,27 @@ echo
     done
   fi
 
-  while read -rp "🙋‍♀️ Is the Ursa repository source-code in the default path $defaultUrsaPath? Type \"no\" to change the location (yes/no) " answer; do
-    if [[ $answer == [nN] || $answer == [nN][oO] ]]; then
-      while read -rp "🙋‍♀️ What's the location where the Ursa repository is?" answer; do
-        if [[ -d "$answer" ]]; then
-          selectedUrsaPath="$answer"
-          
-          break
-        fi
+  if [[ -n "$SELECTED_URSA_PATH" ]]; then
+    selectedUrsaPath="$SELECTED_URSA_PATH"
+  else
+    while read -rp "🙋‍♀️ Is the Ursa repository source-code in the default path $defaultUrsaPath? Type \"no\" to change the location (yes/no) " answer; do
+      if [[ $answer == [nN] || $answer == [nN][oO] ]]; then
+        while read -rp "🙋‍♀️ What's the location where the Ursa repository is?" answer; do
+          if [[ -d "$answer" ]]; then
+            selectedUrsaPath="$answer"
+            
+            break
+          fi
 
-        echo "💩 Uh oh! The path ($answer) doesn't exist, let's try that again..."
-      done
-    elif [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
-      selectedUrsaPath="$defaultUrsaPath"
+          echo "💩 Uh oh! The path ($answer) doesn't exist, let's try that again..."
+        done
+      elif [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
+        selectedUrsaPath="$defaultUrsaPath"
 
-      break;
-    fi
-  done
+        break;
+      fi
+    done
+  fi
 
   echo "🤖 Change work directory to $selectedUrsaPath"
   if ! cd "$selectedUrsaPath"; then
@@ -203,9 +212,7 @@ echo
   fi
 
   if ! ln -s "$HOME/.cargo/bin/ursa-proxy" /usr/local/bin/ursa-proxy; then
-    printf "👹 Oops! Failed to symlink %s to /usr/local/bin/ursa-proxy\n" "$HOME/.cargo/bin/ursa-proxy"
-
-    exit 1
+    printf "💩 Uh oh! Failed to symlink %s to /usr/local/bin/ursa-proxy\n" "$HOME/.cargo/bin/ursa-proxy"
   fi
 
   echo
@@ -218,7 +225,7 @@ echo
 
   printf "🤖 Declare the service and store in the system path\n"
 # Here "no identation" is intentional, do not change
-cat << URSA_PROXY_SERVICE > "$defaultUrsaSystemdServicePath"
+cat << URSA_PROXY_SERVICE > "$defaultUrsaProxySystemdServicePath"
 [Unit]
 Description=Ursa-proxy, for the Decentralized Content Delivery Network (DCDN)
 
@@ -228,22 +235,43 @@ MemoryHigh=1G
 RestartSec=15s
 Restart=always
 ExecStart=$defaultExecCargoProxyCmd
-StandardOutput=null
-StandardError=null
+StandardOutput=append:$defaultUrsaProxyOutputLogAbsPath
+StandardError=append:$defaultUrsaProxyDiagnosticLogAbsPath
 
 [Install]
 WantedBy=multi-user.target
 URSA_PROXY_SERVICE
 
   printf "🤖 Set service file permissions\n"
-  if ! sudo chmod 644 "$defaultUrsaSystemdServicePath"; then
-    echo "💩 Uh oh! Failed to update the file permissions for $defaultUrsaSystemdServicePath"
+  if ! sudo chmod 644 "$defaultUrsaProxySystemdServicePath"; then
+    echo "💩 Uh oh! Failed to update the file permissions for $defaultUrsaProxySystemdServicePath"
   else
     echo "✅ Updated the ursa-proxy service file permissions"
   fi
 
   echo
 
+  printf "🤖 Create logs directory"
+  if ! sudo mkdir -p "$defaultUrsaProxyLogPath"; then
+    read -rp "💩 Uh oh! Failed to create the directory $defaultUrsaProxyLogPath for the logs, you might want to troubleshoot this issue. Press ENTER to continue..."
+  else
+    echo "✅ Created the logs directory $defaultUrsaProxyLogPath"
+  fi
+
+  for file in "$defaultUrsaProxyDiagnosticLogAbsPath" "$defaultUrsaProxyOutputLogAbsPath"; do
+    if ! sudo touch "$file"; then
+      echo "💩 Uh oh! Failed to create $file"
+    else
+      echo "✅ Created the log file $file"
+    fi
+  done
+
+  if ! sudo chmod -R 644 "$defaultUrsaProxyLogPath"; then
+    read -rp "💩 Uh oh! Failed to chmod the directory $defaultUrsaProxyLogPath for the logs, you might want to troubleshoot this issue. Press ENTER to continue..."
+  else
+    echo "✅ Set permissions for $defaultUrsaProxyLogPath"
+  fi
+ 
   printf "🤖 System control daemon reload\n"
   if ! sudo systemctl daemon-reload; then
     echo "💩 Uh oh! The systemctl daemon reload failed"
diff --git a/lets_encrypt b/lets_encrypt
--- a/lets_encrypt
+++ b/lets_encrypt
@@ -117,7 +117,11 @@ domainNameConfSettingsVerificationHandler() {
 
   while read -rp "🙋‍♀️ The Ursa configuration for server has the domain set as $domainCertPath. By proceeding the configuration settings will be reset and lost, is this ok? (yes/no) " answer; do
     if [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
-      rm "$defaultUrsaProxyConfigPath"
+      if ! rm "$defaultUrsaProxyConfigPath"; then
+        echo "💩 Uh oh! failed to remove the $defaultUrsaProxyConfigPath"
+      fi
+
+      createUrsaProxyDir
 
       break;
     elif [[ $answer == [nN] || $answer == [nN][oO] ]]; then
@@ -128,28 +132,30 @@ domainNameConfSettingsVerificationHandler() {
   done  
 }
 
+createUrsaProxyDir() {
+  echo "✅ Create Ursa proxy directory"
+  mkdir -p "$defaultUrsaProxyDir"
+  touch "$defaultUrsaProxyConfigPath"  
+}
+
 ursaServerConfigurationHandler() {
   if [[ ! -d "$defaultUrsaProxyDir" ]]; then
-    echo "✅ Create Ursa proxy directory"
-    mkdir -p "$defaultUrsaProxyDir"
-    touch "$defaultUrsaProxyConfigPath"
+    createUrsaProxyDir
   else
     if grep -qi "$defaultLetsEncryptCertificatesLivePath" "$defaultUrsaProxyConfigPath" && grep -qi "[[server]]" "$defaultUrsaProxyConfigPath"; then
       echo "✅ Ursa server proxy configuration exists"
       echo
 
       # Check if domain name is correct in the settings file
-      domainNameConfSettingsVerificationHandler "$1"
+      domainNameConfSettingsVerificationHandler
 
       return 0
     fi
   fi
 
-  if [[ $1 -eq "1" ]]; then
-
-    if [[ ! -f "$defaultUrsaProxyConfigPath" ]]; then
-      touch "$defaultUrsaProxyConfigPath"
-    fi
+  if [[ ! -f "$defaultUrsaProxyConfigPath" ]]; then
+    touch "$defaultUrsaProxyConfigPath"
+  fi
 
 # Here "no identation" is intentional, do not change
 # The top empty line at the top is intentional
@@ -158,11 +164,8 @@ echo "# Server without TLS.
 proxy_pass = \"127.0.0.1:4069\"
 listen_addr = \"0.0.0.0:80\"
 serve_dir_path = \".well-known\"
-" > "$defaultUrsaProxyConfigPath" || exit 1
-elif [[ $1 -eq "2" ]]; then
-# Here "no identation" is intentional, do not change
-# The top empty line at the top is intentional
-echo "# Server with TLS
+
+# Server with TLS
 [[server]]
 proxy_pass = \"127.0.0.1:4069\"
 listen_addr = \"0.0.0.0:443\"
@@ -176,7 +179,6 @@ key_path = \"$defaultLetsEncryptCertificatesLivePath/$selectedDomainName/privkey
 [admin]
 addr = \"0.0.0.0:8881\"
 " > "$defaultUrsaProxyConfigPath" || exit 1
-fi
 
   echo "✅ Updated the config.toml by including the [server] settings"
   echo
@@ -195,7 +197,8 @@ runHealthCheckForHTTPS() {
   fi
 }
 
-
+introAscii() {
+# Obs: The cat indentation is intentional, do not change
 cat << "URSA_START_SCRIPT"
 
          __
@@ -209,16 +212,21 @@ cat << "URSA_START_SCRIPT"
      `---''---`
 URSA_START_SCRIPT
 
-echo
-echo "⭐️ Let's Encrypt setup script, for the Fleek Network Ursa-proxy server ⭐️"
-echo
-echo "★★★★★★★★★ 🌍 Website https://fleek.network"
-echo "★★★★★★★★★ 📚 Documentation https://docs.fleek.network"
-echo "★★★★★★★★★ 💾 Git repository https://github.com/fleek-network/ursa"
-echo "★★★★★★★★★ 🤖 Discord https://discord.gg/fleekxyz"
-echo "★★★★★★★★★ 🐤 Twitter https://twitter.com/fleek_net"
-echo "★★★★★★★★★ 🎨 Ascii art by https://www.asciiart.eu"
-echo
+  echo
+  echo "⭐️ Let's Encrypt setup script, for the Fleek Network Ursa-proxy server ⭐️"
+  echo
+  echo "★★★★★★★★★ 🌍 Website https://fleek.network"
+  echo "★★★★★★★★★ 📚 Documentation https://docs.fleek.network"
+  echo "★★★★★★★★★ 💾 Git repository https://github.com/fleek-network/ursa"
+  echo "★★★★★★★★★ 🤖 Discord https://discord.gg/fleekxyz"
+  echo "★★★★★★★★★ 🐤 Twitter https://twitter.com/fleek_net"
+  echo "★★★★★★★★★ 🎨 Ascii art by https://www.asciiart.eu"
+  echo
+}
+
+if [[ -z ${SKIP_INTRO+x} ]]; then
+  introAscii
+fi
 
 (
   exec < /dev/tty;
@@ -260,23 +268,27 @@ echo
     fi
   fi
 
-  while read -rp "🙋‍♀️ Is the Ursa repository source-code in the default path $defaultUrsaPath? Type \"no\" to change the location (yes/no) " answer; do
-    if [[ $answer == [nN] || $answer == [nN][oO] ]]; then
-      while read -rp "🙋‍♀️ What's the location where the Ursa repository is?" answer; do
-        if [[ -d "$answer" ]]; then
-          selectedUrsaPath="$answer"
-          
-          break
-        fi
+  if [[ -n "$SELECTED_URSA_PATH" ]]; then
+    selectedUrsaPath="$SELECTED_URSA_PATH"
+  else
+    while read -rp "🙋‍♀️ Is the Ursa repository source-code in the default path $defaultUrsaPath? Type \"no\" to change the location (yes/no) " answer; do
+      if [[ $answer == [nN] || $answer == [nN][oO] ]]; then
+        while read -rp "🙋‍♀️ What's the location where the Ursa repository is?" answer; do
+          if [[ -d "$answer" ]]; then
+            selectedUrsaPath="$answer"
+            
+            break
+          fi
 
-        echo "💩 Uh oh! The path ($answer) doesn't exist, let's try that again..."
-      done
-    elif [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
-      selectedUrsaPath="$defaultUrsaPath"
+          echo "💩 Uh oh! The path ($answer) doesn't exist, let's try that again..."
+        done
+      elif [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
+        selectedUrsaPath="$defaultUrsaPath"
 
-      break;
-    fi
-  done
+        break;
+      fi
+    done
+  fi
 
   echo "🤖 Change work directory to $selectedUrsaPath"
   if ! cd "$selectedUrsaPath"; then
@@ -288,55 +300,63 @@ echo
 
   detectedIpAddress=$(getIpAddress)
 
-  printf -v prompt "🤖 What's your domain name address?"
-  while read -rp "$prompt"$'\n> ' answer; do
-    if confirmDomainName "$answer"; then
-      selectedDomainName="$answer"
-      break
-    fi
+  if [[ -n "$SELECTED_DOMAIN_NAME" ]]; then
+    selectedDomainName="$SELECTED_DOMAIN_NAME"
+  else
+    printf -v prompt "🤖 What's your domain name address?"
+    while read -rp "$prompt"$'\n> ' answer; do
+      if confirmDomainName "$answer"; then
+        selectedDomainName="$answer"
+        break
+      fi
 
-    printf "💩 The domain name provided is not valid!\n"
+      printf "💩 The domain name provided is not valid!\n"
 
-    [[ "$answer" =~ http* ]] && echo "💡 Just type the domain name address, there's no need for http:// or https:// e.g. mynode.example.com"
-  done
+      [[ "$answer" =~ http* ]] && echo "💡 Just type the domain name address, there's no need for http:// or https:// e.g. mynode.example.com"
+    done
+  fi
 
   echo
 
-  printf "The server public IP address the domain is pointing to is required! We found the public IP address for this machine to be %s\n" "$detectedIpAddress"
-  printf -v prompt "🤖 Is the domain name %s pointing to the public IP address %s? (yes/no) " "$selectedDomainName" "$detectedIpAddress"
-  while read -rp "$prompt"$'\n> ' answer; do
-    if [[ $answer == [nN] || $answer == [nN][oO] ]]; then
-      printf "💩 Oh no! The %s has to point to the server public IP address %s. Alternatively, you can check our guides and install the Ursa CLI on your own, but is likely that the security of your server will be taken into account by the rewards mechanism. To avoid disappointment follow the recomendations!\n" "$selectedDomainName" "$detectedIpAddress"  
-
-      continue
-    fi
-
-    if [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
-      # Dig is required for the next step
-      if ! dpkg -s bind9-dnsutils >/dev/null; then
-        echo "🙋‍♀️ bind9-dnsutils is required, we'll go ahead and install it"
-        printf "🤖 Update and upgrade apt-get\n"
-        sudo DEBIAN_FRONTEND=noninteractive apt-get update -yq
-        sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -yq
-
-        if ! sudo DEBIAN_FRONTEND=noninteractive apt-get install bind9-dnsutils -y; then
-          printf "👹 Oops! Failed to install dnsutils for some reason...\n"
-        fi
-      fi
-
-      if ! dig "$selectedDomainName" +nostats +nocomments +nocmd | tr -d '\t' | grep "A$detectedIpAddress" >/dev/null 2>&1 ; then
-        printf "💩 Oh no! The %s doesn't seem to point to the IP address %s\n" "$selectedDomainName" "$detectedIpAddress"
+  if [[ -n "$SELECTED_IP_ADDRESS" ]]; then
+    selectedIpAddress="$SELECTED_IP_ADDRESS"
+  else
+    printf "The server public IP address the domain is pointing to is required! We found the public IP address for this machine to be %s\n" "$detectedIpAddress"
+    printf -v prompt "🤖 Is the domain name %s pointing to the public IP address %s? (yes/no) " "$selectedDomainName" "$detectedIpAddress"
+    while read -rp "$prompt"$'\n> ' answer; do
+      if [[ $answer == [nN] || $answer == [nN][oO] ]]; then
+        printf "💩 Oh no! The %s has to point to the server public IP address %s. Alternatively, you can check our guides and install the Ursa CLI on your own, but is likely that the security of your server will be taken into account by the rewards mechanism. To avoid disappointment follow the recomendations!\n" "$selectedDomainName" "$detectedIpAddress"  
 
         continue
       fi
 
-      selectedIpAddress="$detectedIpAddress"
+      if [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
+        # Dig is required for the next step
+        if ! dpkg -s bind9-dnsutils >/dev/null; then
+          echo "🙋‍♀️ bind9-dnsutils is required, we'll go ahead and install it"
+          printf "🤖 Update and upgrade apt-get\n"
+          sudo DEBIAN_FRONTEND=noninteractive apt-get update -yq
+          sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -yq
 
-      break
-    fi
+          if ! sudo DEBIAN_FRONTEND=noninteractive apt-get install bind9-dnsutils -y; then
+            printf "👹 Oops! Failed to install dnsutils for some reason...\n"
+          fi
+        fi
 
-    printf "😅 Sorry! Try that again...\n"
-  done
+        if ! dig "$selectedDomainName" +nostats +nocomments +nocmd | tr -d '\t' | grep "A$detectedIpAddress" >/dev/null 2>&1 ; then
+          printf "💩 Oh no! The %s doesn't seem to point to the IP address %s\n" "$selectedDomainName" "$detectedIpAddress"
+
+          continue
+        fi
+
+        selectedIpAddress="$detectedIpAddress"
+
+        break
+      fi
+
+      printf "😅 Sorry! Try that again...\n"
+    done
+  fi
 
   echo
 
@@ -387,45 +407,53 @@ echo
 
   echo
 
-  printf "Let's Encrypt provides SSL/TLS Certificates for securing the communications. A valid email address is required by the Let's Encrypt organisation (Fleek Network is not affiliated and does NOT store the email address).\n"
-  printf -v prompt "What's your email address?"
-  while read -rp "$prompt"$'\n> ' answer; do
-    if confirmEmailAddress "$answer"; then
-      selectedEmailAddress="$answer"
-      break
-    fi
+  if [[ -n "$SELECTED_EMAIL_ADDRESS" ]]; then
+    selectedEmailAddress="$SELECTED_EMAIL_ADDRESS"
+  else
+    printf "Let's Encrypt provides SSL/TLS Certificates for securing the communications. A valid email address is required by the Let's Encrypt organisation (Fleek Network is not affiliated and does NOT store the email address).\n"
+    printf -v prompt "What's your email address?"
+    while read -rp "$prompt"$'\n> ' answer; do
+      if confirmEmailAddress "$answer"; then
+        selectedEmailAddress="$answer"
+        break
+      fi
 
-    printf "💩 Oh no! The email address doesn't seem valid, try again...\n"
-  done
+      printf "💩 Oh no! The email address doesn't seem valid, try again...\n"
+    done
+  fi
 
   echo
 
   # Ursa server configuration handler to ensure the settings exist and correct
-  ursaServerConfigurationHandler 1
+  ursaServerConfigurationHandler
 
   echo "🤖 Ursa proxy"
 
   if systemctl list-units --full -all | grep -q "ursa-proxy.service"; then
     echo "✅ The Ursa-proxy service is available"
     echo
-
-    if systemctl is-active --quiet ursa-proxy; then
-      echo "🦖 We'll stop the ursa-proxy for a bit, for certbot standalone web server"
-      sudo systemctl stop ursa-proxy
-    fi
   else
     while read -rp "🙋‍♀️ The ursa-proxy service was not found. Would you like to have it installed now? (yes/no) " answer; do
       if [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
         read -rp "💡 The ursa-proxy service installer is a separate process that will be executed, when complete, the Let's Encrypt setup will continue. Press ENTER to continue..."
 
-        if ! curl -s https://get.fleek.network/install_ursa_proxy | bash; then
-          echo "👹 Oh no! Failed to install the ursa-proxy"
+        # INFO: set `USE_BRANCH_NAME_FOR_GH_RAW` to use the Github raw locales for testing
+        # e.g., USE_BRANCH_NAME_FOR_GH_RAW="feat/localization" ./install
+        if [[ -n ${USE_BRANCH_NAME_FOR_GH_RAW+x} ]]; then
+          echo "🥷 Switch to branch $USE_BRANCH_NAME_FOR_GH_RAW"
 
-          exit 1
+          if ! curl -s "https://raw.githubusercontent.com/fleek-network/get.fleek.network/$USE_BRANCH_NAME_FOR_GH_RAW/scripts/install_ursa_proxy" | bash; then
+            echo "👹 Oh no! Failed to install the ursa-proxy"
+
+            exit 1
+          fi
+        else
+          if ! curl -s "https://get.fleek.network/install_ursa_proxy" | bash; then
+            echo "👹 Oh no! Failed to install the ursa-proxy"
+
+            exit 1
+          fi
         fi
-
-        echo "🦖 We'll stop the ursa-proxy for now. The certbot standalone web server will launch for the certification process shortly"
-        sudo systemctl stop ursa-proxy
 
         break;
       elif [[ $answer == [nN] || $answer == [nN][oO] ]]; then
@@ -435,6 +463,9 @@ echo
       fi
     done
   fi
+
+  echo "🦖 We'll stop the ursa-proxy for a bit, for certbot standalone web server"
+  sudo systemctl stop ursa-proxy
 
   echo "🤖 Certbot"
   if ! hasCommand certbot; then
@@ -544,7 +575,12 @@ echo
   echo
 
   echo "🤖 Set Ursa proxy configuration for SSL/TLS"
-  ursaServerConfigurationHandler 2
+  if ! curl -X POST 0.0.0.0:8881/reload-tls-config; then
+    echo "💩 Uh oh! Failed to reload the ursa-proxy TLS configuration."
+    echo
+
+    sleep 3
+  fi
 
   echo
 
