deploy: 43920bb6ebf47f2fe9b5a50010fa02bbd639542b

diff --git a/install_native b/install_native
--- a/install_native
+++ b/install_native
@@ -547,25 +547,25 @@ fi
 
 echo
 
-printf "🤖 Symlink the Ursa CLI binary to /usr/bin. By default rustup should've set the .cargo/bin into your system PATH, in any case we'll attempt to symlink to ensure ursa is available globally\n"
+printf "🤖 Symlink the Ursa CLI binary to /usr/local/bin. By default rustup should've set the .cargo/bin into your system PATH, in any case we'll attempt to symlink to ensure ursa is available globally\n"
 if [[ -f "$HOME/.cargo/bin/ursa" ]]; then
-  if ! ln -s "$HOME/.cargo/bin/ursa" /usr/bin/ursa; then
-    printf "👹 Oops! Failed to symlink %s to /usr/bin/ursa\n" "$HOME/.cargo/bin/ursa"
+  if ! ln -s "$HOME/.cargo/bin/ursa" /usr/local/bin/ursa; then
+    printf "👹 Oops! Failed to symlink %s to /usr/local/bin/ursa\n" "$HOME/.cargo/bin/ursa"
     echo
-    read -rp "😅 After the installation, if ursa cli command is not available globally, then you need to add $HOME/.cargo/bin/ursa to your system PATH or symlink the binary to /usr/bin/ursa, as we've failed to do it. Press ENTER to continue..."
+    read -rp "😅 After the installation, if ursa cli command is not available globally, then you need to add $HOME/.cargo/bin/ursa to your system PATH or symlink the binary to /usr/local/bin/ursa, as we've failed to do it. Press ENTER to continue..."
   fi
 else
-  if ! ln -s "$selectedUrsaPath/target/release/ursa" /usr/bin/ursa; then
-    printf "👹 Oops! Failed to symlink %s to /usr/bin/ursa\n" "$selectedUrsaPath/target/release/ursa"
+  if ! ln -s "$selectedUrsaPath/target/release/ursa" /usr/local/bin/ursa; then
+    printf "👹 Oops! Failed to symlink %s to /usr/local/bin/ursa\n" "$selectedUrsaPath/target/release/ursa"
     echo
-    read -rp "😅 After the installation, if ursa cli command is not available globally, then you need to add $selectedUrsaPath/target/release/ursa to your system PATH or symlink the binary to /usr/bin/ursa, as we've failed to do it. Press ENTER to continue..."
+    read -rp "😅 After the installation, if ursa cli command is not available globally, then you need to add $selectedUrsaPath/target/release/ursa to your system PATH or symlink the binary to /usr/local/bin/ursa, as we've failed to do it. Press ENTER to continue..."
   fi
 fi
 
 echo
 
 printf "👌 Great! You have successfully installed required packages, libraries, have compiled and installed Ursa\n\n"
-printf "The Ursa CLI should be available globally, there's a symlink to the /usr/bin/ursa. Which means that from now on you can start a Network Node by typing ursa\n"
+printf "The Ursa CLI should be available globally, there's a symlink to the /usr/local/bin/ursa. Which means that from now on you can start a Network Node by typing ursa\n"
 
 echo
 
@@ -909,7 +909,7 @@ Type=simple
 MemoryHigh=8G
 RestartSec=15s
 Restart=always
-ExecStart=/usr/bin/ursa
+ExecStart=ursa
 StandardOutput=append:$defaultUrsaOutputLogAbsPath
 StandardError=append:$defaultUrsaDiagnosticLogAbsPath
 
diff --git a/install_ursa_proxy b/install_ursa_proxy
--- a/install_ursa_proxy
+++ b/install_ursa_proxy
@@ -202,6 +202,12 @@ echo
     exit 1
   fi
 
+  if ! ln -s "$HOME/.cargo/bin/ursa-proxy" /usr/local/bin/ursa-proxy; then
+    printf "👹 Oops! Failed to symlink %s to /usr/local/bin/ursa-proxy\n" "$HOME/.cargo/bin/ursa-proxy"
+
+    exit 1
+  fi
+
   echo
 
   if ! hasCommand ursa-proxy; then
