refactor: 💡 use bind9-dnsutils for dig

diff --git a/install_native b/install_native
--- a/install_native
+++ b/install_native
@@ -356,20 +356,20 @@ while read -rp "$prompt"$'\n> ' answer; do
 
   if [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
     # Dig is required for the next step
-    if ! dpkg -s dnsutils >/dev/null; then
-      while read -rp "🙋‍♀️ Dnsutils is required, can we go ahead and install it? (yes/no) " answer; do
+    if dpkg -s bind9-dnsutils >/dev/null; then
+      while read -rp "🙋‍♀️ bind9-dnsutils is required, can we go ahead and install it? (yes/no) " answer; do
         if [[ "$answer" == [yY] || "$answer" == [yY][eE][sS] ]]; then
           printf "🤖 Update and upgrade apt-get\n"
           sudo DEBIAN_FRONTEND=noninteractive apt-get update -yq
           sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -yq
 
-          if ! sudo DEBIAN_FRONTEND=noninteractive apt-get install dnsutils -y; then
+          if ! sudo DEBIAN_FRONTEND=noninteractive apt-get install bind9-dnsutils -y; then
             printf "👹 Oops! Failed to install dnsutils for some reason...\n"
           fi
 
           break
         elif [[ "$answer" == [nN] || "$answer" == [nN][oO] ]]; then
-          printf "🦖 Exited! Dnsutils is required\n"
+          printf "🦖 Exited! bind9-dnsutils is required\n"
 
           exit 1
         fi
