deploy: 7e0d2b43262e0130661c89afd754c7f9049e9e80

diff --git a/lets_encrypt b/lets_encrypt
--- a/lets_encrypt
+++ b/lets_encrypt
@@ -178,6 +178,11 @@ fi
   fi
 
   if [[ $1 -eq "1" ]]; then
+
+    if [[ ! -f "$defaultUrsaProxyConfigPath" ]]; then
+      touch "$defaultUrsaProxyConfigPath"
+    fi
+
 # Here "no identation" is intentional, do not change
 # The top empty line at the top is intentional
 echo "
@@ -214,34 +219,6 @@ fi
   hasCommand() {
     command -v "$1" >/dev/null 2>&1
   }
-
-  echo "🤖 Ursa proxy"
-  ursaProxyPID=$(pidof ursa-proxy | tr ' ' '\n')
-
-  if [[ ! "$ursaProxyPID" ]]; then
-    if hasCommand ursa-proxy; then
-      while read -rp "🙋‍♀️ We found ursa-proxy. Would you like to start it now? (yes/no)" answer; do
-        if [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
-          if ! sudo systemctl restart ursa-proxy; then
-            printf "👹 Oops! Failed to start the ursa-proxy systemd service\n"
-
-            exit 1
-          fi
-
-          ursaProxyPID=$(pidof ursa-proxy | tr ' ' '\n')
-          break;
-        elif [[ $answer == [nN] || $answer == [nN][oO] ]]; then
-          echo "🦖 The Lets Encrypt setup was interrupted because the ursa-proxy has not started. Make sure that you start the ursa-proxy before you retry..."
-
-          exit 1
-        fi
-      done
-    else
-      printf "👹 Oops! The ursa-proxy process has to be running. Make sure that you start the ursa-proxy before you retry...\n"
-
-      exit 1
-    fi
-  fi
 
   while read -rp "🙋‍♀️ Is the Ursa repository source-code in the default path $defaultUrsaPath? Type \"no\" to change the location (yes/no) " answer; do
     if [[ $answer == [nN] || $answer == [nN][oO] ]]; then
@@ -365,6 +342,34 @@ fi
 
   # Ursa server configuration handler to ensure the settings exist and correct
   ursaServerConfigurationHandler 1
+
+  echo "🤖 Ursa proxy"
+  ursaProxyPID=$(pidof ursa-proxy | tr ' ' '\n')
+
+  if [[ ! "$ursaProxyPID" ]]; then
+    if hasCommand ursa-proxy; then
+      while read -rp "🙋‍♀️ We found ursa-proxy. Would you like to start it now? (yes/no)" answer; do
+        if [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
+          if ! sudo systemctl restart ursa-proxy; then
+            printf "👹 Oops! Failed to start the ursa-proxy systemd service\n"
+
+            exit 1
+          fi
+
+          ursaProxyPID=$(pidof ursa-proxy | tr ' ' '\n')
+          break;
+        elif [[ $answer == [nN] || $answer == [nN][oO] ]]; then
+          echo "🦖 The Lets Encrypt setup was interrupted because the ursa-proxy has not started. Make sure that you start the ursa-proxy before you retry..."
+
+          exit 1
+        fi
+      done
+    else
+      printf "👹 Oops! The ursa-proxy process has to be running. Make sure that you start the ursa-proxy before you retry...\n"
+
+      exit 1
+    fi
+  fi
 
   printf "🚑 Ursa proxy health-check\n"
   pingAttempts=0
