deploy: 0d6a745545d1e05a0b3644026053d07c3e1c0ca4

diff --git a/transfer_system_user_setup_ownership b/transfer_system_user_setup_ownership
--- a/transfer_system_user_setup_ownership
+++ b/transfer_system_user_setup_ownership
@@ -229,7 +229,16 @@ moveDirectoryFromTo() {
   echo
 
   targetLightningSourceCodePath="/home/$targetUsername/$defaultBasePath"
-  targetRustReleasePath="$targetLightningSourceCodePath/target/release/$defaultCLIBuildName"
+  
+  if [[ -f "$HOME/.cargo/bin/$defaultCLIBuildName" ]]; then
+    targetRustReleasePath="/home/$targetUsername/.cargo/bin/$defaultCLIBuildName"
+  elif [[ -f "$CARGO_HOME/bin/$defaultCLIBuildName" ]]; then
+    targetRustReleasePath="$CARGO_HOME/bin/$defaultCLIBuildName"
+  else
+    echo "👹 Oops! The binary $defaultCLIBuildName was not found!"
+
+    exit 1
+  fi
 
   if [[ ! -d "$targetLightningSourceCodePath" ]]; then
     if ! sudo mkdir -p "$targetLightningSourceCodePath"; then
@@ -281,7 +290,7 @@ moveDirectoryFromTo() {
     ((warningCount++))    
   fi
 
-  if ! sudo ln -s "$targetLightningSourceCodePath/target/release/$defaultCLIBuildName" "$defaultSymlinkPath"; then
+  if ! sudo ln -s "$targetRustReleasePath" "$defaultSymlinkPath"; then
     echo "⚠️ WARNING: Failed to create symlink $defaultSymlinkPath"
 
     ((warningCount++))
diff --git a/update b/update
--- a/update
+++ b/update
@@ -23,6 +23,22 @@ defaultLightningBasePath="$HOME/.$defaultName"
 defaultLightningConfigFilename="config.toml"
 defaultLightningConfigPath="$defaultLightningBasePath/$defaultLightningConfigFilename"
 defaultTempLogFilePath="/var/tmp"
+defaultMinRustVersion="1.75.0"
+
+# Utils
+isRustVersionGtMinReq() {
+ if [[ "$1" == "$defaultMinRustVersion" ]]; then
+   return 0
+ fi
+
+ head=$(printf "$defaultMinRustVersion\n$1\n" | sort -rV | head -n1)
+
+ if [[ "$head" == "$defaultMinRustVersion" ]]; then
+   return 1
+ fi
+
+ return 0
+}
 
 (
   exec < /dev/tty;
@@ -85,6 +101,16 @@ defaultTempLogFilePath="/var/tmp"
     exit 1
   fi
 
+  if ! isRustVersionGtMinReq "$(cargo version | cut -d " " -f 2)"; then
+    echo "🤖 Rust is going to be updated..."
+
+    if ! rustup update; then
+      echo "👹 Oops! Failed to update rust for some reason..."
+
+      exit 1
+    fi
+  fi
+
   if [[ ! -d "$defaultLightningPath" ]]; then
     defaultLightningPath="$(find . -type f -wholename "*core/node/Cargo.toml" -exec dirname "{}" \; |sort -zu |sed -z 's/$/\n/')"
 
@@ -144,7 +170,7 @@ defaultTempLogFilePath="/var/tmp"
   fi
 
   printf "🤖 Build and install the %s CLI\n" "$defaultName"
-  if ! cargo +stable build --release; then
+  if ! cargo +stable install --locked --path core/cli; then
     printf "👹 Oops! Failed to build and install the %s CLI. If you are experiencing issues, help us improve by letting us know in our Discord %s\n" "$defaultName" "$defaultDiscordUrl"
 
     exit 1
@@ -156,10 +182,12 @@ defaultTempLogFilePath="/var/tmp"
     fi
   fi
 
-  if ! sudo ln -s "$defaultLightningPath/target/$defaultTargetName/$defaultCLIBuildName" /usr/local/bin/$defaultCLIAlias; then
-    printf "👹 Oops! Failed to symlink %s to /usr/local/bin/$defaultCLIAlias\n" "$defaultLightningPath/target/$defaultTargetName/$defaultCLIBuildName"
-    echo
-    read -rp "😅 After the installation, if $defaultName $defaultCLIBuildName CLI command is unavailable globally, then you need to add $defaultLightningPath/target/$defaultTargetName/$defaultCLIBuildName to your system PATH or symlink the binary to /usr/local/bin/$defaultCLIAlias, as we've failed to do it. Press ENTER to continue..."
+  if [[ -f "$HOME/.cargo/bin/$defaultName" ]]; then
+    if ! sudo ln -s "$HOME/.cargo/bin/$defaultName" /usr/local/bin/$defaultCLIAlias; then
+      printf "👹 Oops! Failed to symlink %s to /usr/local/bin/%s\n" "$HOME/.cargo/bin/$defaultName" "$defaultName"
+      echo
+      read -rp "😅 After the installation, if $defaultName CLI command is not available globally, then you need to add $HOME/.cargo/bin/lightning to your system PATH or symlink the binary to /usr/local/bin/$defaultName, as we've failed to do it. Press ENTER to continue..."
+    fi
   fi
 
   echo "🚑 Verify $defaultLightningConfigPath..."
