refactor: 💡 ursa proxy config toml (revised) (#28)

diff --git a/scripts/install_docker b/scripts/install_docker
--- a/scripts/install_docker
+++ b/scripts/install_docker
@@ -35,7 +35,7 @@
 # - Do a health check to confirm the Fleek Network Node is running
 #
 # Contributing?
-# - If you'd like to test changes locally use the env var `USE_BRANCH_NAME_FOR_GH_RAW`, for remote locales pulls
+# - If you'd like to test changes locally use the env var `USE_BRANCH_NAME_FOR_GH_RAW` and `URSA_BRANCH`, for remote locales pulls
 #
 # Found an issue? Please report it here: https://github.com/fleek-network/get.fleek.network
 
@@ -72,6 +72,7 @@ defaultUrsaProxyDir="$defaultUrsaBasePath/proxy"
 defaultUrsaProxyConfigPath="$defaultUrsaProxyDir/config.toml"
 defaultLetsEncryptCertificatesLivePath="/etc/letsencrypt/live"
 defaultDockerNetworkUrsaHostname="full-node-ursa-1"
+defaultDockerNetworkUrsaProxyHostname="full-node-ursa-proxy-1"
 
 # App state
 userSelectedLanguage=""
@@ -432,6 +433,14 @@ dockerComposeExec() {
     sudo docker compose "$@"
   else
     sudo docker-compose "$@"
+  fi
+}
+
+yqExec() {
+  if ! sudo yq "$@" >/dev/null 2>&1; then
+    if ! sudo /snap/bin/yq "$@"; then
+      echo "😅 The yq fallback failed"
+    fi
   fi
 }
 
@@ -1188,11 +1197,9 @@ ursaServerConfigurationHandler() {
     sudo touch "$defaultUrsaProxyConfigPath"
   fi
 
-  if [[ $1 -eq "1" ]]; then
-
-    if [[ ! -f "$defaultUrsaProxyConfigPath" ]]; then
-      sudo touch "$defaultUrsaProxyConfigPath"
-    fi
+  if [[ ! -f "$defaultUrsaProxyConfigPath" ]]; then
+    sudo touch "$defaultUrsaProxyConfigPath"
+  fi
 
 # Here "no identation" is intentional, do not change
 # The top empty line at the top is intentional
@@ -1201,11 +1208,8 @@ echo "# Server without TLS.
 proxy_pass = \"$defaultDockerNetworkUrsaHostname:4069\"
 listen_addr = \"0.0.0.0:80\"
 serve_dir_path = \".well-known\"
-" | sudo tee "$defaultUrsaProxyConfigPath" || exit 1
-elif [[ $1 -eq "2" ]]; then
-# Here "no identation" is intentional, do not change
-# The top empty line at the top is intentional
-echo "# Server with TLS
+
+# Server with TLS
 [[server]]
 proxy_pass = \"$defaultDockerNetworkUrsaHostname:4069\"
 listen_addr = \"0.0.0.0:443\"
@@ -1219,7 +1223,7 @@ key_path = \"$defaultLetsEncryptCertificatesLivePath/$userDomainName/privkey.pem
 [admin]
 addr = \"0.0.0.0:8881\"
 " | sudo tee "$defaultUrsaProxyConfigPath" || exit 1
-fi
+
   # TODO: Create translation
   echo "✅ Updated the config.toml by including the [server] settings"
   echo
@@ -1236,7 +1240,7 @@ initLetsEncrypt() {
   fi
 
   # Ursa server configuration handler to ensure the settings exist and correct
-  ursaServerConfigurationHandler 1
+  ursaServerConfigurationHandler
 
   if [[ ! -f "$defaultUrsaProxyConfigPath" ]]; then
     # TODO: Create translation
@@ -1375,7 +1379,7 @@ verifyDepsOrInstall() {
         showOkMessage "${transl[verify_deps_installed_via_package_manager]/_name_/$name} snap"
 
         # ensure snap is in the PATH and pkgs
-        PATH="$PATH:/snap/bin"
+        export PATH="$PATH:/snap/bin"
 
         return 0
       fi
@@ -1557,7 +1561,17 @@ setupSSLTLS() {
 
   # TODO: Create translation
   echo "🤖 Set Ursa proxy configuration for SSL/TLS"
-  ursaServerConfigurationHandler 2
+  if ! dockerComposeExec -f "$defaultDockerComposeYmlRelativePath" run \
+    --rm --entrypoint "\
+    if ! curl -X POST 0.0.0.0:8881/reload-tls-config; then
+      exit 1;
+    fi
+    " "$defaultDockerNetworkUrsaProxyHostname"; then
+    echo "💩 Uh oh! Failed to reload the ursa-proxy TLS configuration."
+    echo
+
+    sleep 3
+  fi
 
   if [[ ! -f "$defaultUrsaProxyConfigPath" ]]; then
     # TODO: Create translation
@@ -1611,7 +1625,7 @@ onLatestPreference() {
       break
     elif [[ "$data" -eq 0 ]]; then
       for name in "ursa" "ursa-proxy"; do
-        if ! sudo yq -ie "del(.services.$name.build)" "$defaultDockerComposeYmlRelativePath" >/dev/null 2>&1; then
+        if ! yqExec -ie "del(.services.$name.build)" "$defaultDockerComposeYmlRelativePath" >/dev/null 2>&1; then
           echo "👹 Oops! Failed to remove declare service build $name from $defaultDockerComposeYmlRelativePath"
         else
           echo "✅ Deleted docker-compose.yml .services.$name.build"
@@ -1619,13 +1633,13 @@ onLatestPreference() {
 
         currentImageName="${defaultGHCRImagePlaceholderUrl/_imageName_/$name}"
 
-        if ! sudo yq -i ".services.$name.image = \"$currentImageName\"" "$defaultDockerComposeYmlRelativePath" >/dev/null 2>&1; then
+        if ! yqExec -i ".services.$name.image = \"$currentImageName\"" "$defaultDockerComposeYmlRelativePath" >/dev/null 2>&1; then
           echo "👹 Oops! Failed to set service $name image in $defaultDockerComposeYmlRelativePath"
         else
           echo "✅ Set service in docker-compose.yml .services.$name.image"
         fi
 
-        if ! sudo yq ".services.$name.image" "$defaultDockerComposeYmlRelativePath" | grep -q "$currentImageName" || ! sudo yq ".services.$name.build" "$defaultDockerComposeYmlRelativePath" | grep -qE "null|no matches found"; then
+        if ! yqExec ".services.$name.image" "$defaultDockerComposeYmlRelativePath" | grep -q "$currentImageName" || ! yqExec ".services.$name.build" "$defaultDockerComposeYmlRelativePath" | grep -qE "null|no matches found"; then
           echo
           echo "💩 ${transl[on_latest_preference_uh_oh_failed_modify_docker_compose_yaml]}"
 
diff --git a/scripts/lets_encrypt b/scripts/lets_encrypt
--- a/scripts/lets_encrypt
+++ b/scripts/lets_encrypt
@@ -117,7 +117,11 @@ domainNameConfSettingsVerificationHandler() {
 
   while read -rp "🙋‍♀️ The Ursa configuration for server has the domain set as $domainCertPath. By proceeding the configuration settings will be reset and lost, is this ok? (yes/no) " answer; do
     if [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
-      rm "$defaultUrsaProxyConfigPath"
+      if ! rm "$defaultUrsaProxyConfigPath"; then
+        echo "💩 Uh oh! failed to remove the $defaultUrsaProxyConfigPath"
+      fi
+
+      createUrsaProxyDir
 
       break;
     elif [[ $answer == [nN] || $answer == [nN][oO] ]]; then
@@ -128,28 +132,30 @@ domainNameConfSettingsVerificationHandler() {
   done  
 }
 
+createUrsaProxyDir() {
+  echo "✅ Create Ursa proxy directory"
+  mkdir -p "$defaultUrsaProxyDir"
+  touch "$defaultUrsaProxyConfigPath"  
+}
+
 ursaServerConfigurationHandler() {
   if [[ ! -d "$defaultUrsaProxyDir" ]]; then
-    echo "✅ Create Ursa proxy directory"
-    mkdir -p "$defaultUrsaProxyDir"
-    touch "$defaultUrsaProxyConfigPath"
+    createUrsaProxyDir
   else
     if grep -qi "$defaultLetsEncryptCertificatesLivePath" "$defaultUrsaProxyConfigPath" && grep -qi "[[server]]" "$defaultUrsaProxyConfigPath"; then
       echo "✅ Ursa server proxy configuration exists"
       echo
 
       # Check if domain name is correct in the settings file
-      domainNameConfSettingsVerificationHandler "$1"
+      domainNameConfSettingsVerificationHandler
 
       return 0
     fi
   fi
 
-  if [[ $1 -eq "1" ]]; then
-
-    if [[ ! -f "$defaultUrsaProxyConfigPath" ]]; then
-      touch "$defaultUrsaProxyConfigPath"
-    fi
+  if [[ ! -f "$defaultUrsaProxyConfigPath" ]]; then
+    touch "$defaultUrsaProxyConfigPath"
+  fi
 
 # Here "no identation" is intentional, do not change
 # The top empty line at the top is intentional
@@ -158,11 +164,8 @@ echo "# Server without TLS.
 proxy_pass = \"127.0.0.1:4069\"
 listen_addr = \"0.0.0.0:80\"
 serve_dir_path = \".well-known\"
-" > "$defaultUrsaProxyConfigPath" || exit 1
-elif [[ $1 -eq "2" ]]; then
-# Here "no identation" is intentional, do not change
-# The top empty line at the top is intentional
-echo "# Server with TLS
+
+# Server with TLS
 [[server]]
 proxy_pass = \"127.0.0.1:4069\"
 listen_addr = \"0.0.0.0:443\"
@@ -176,7 +179,6 @@ key_path = \"$defaultLetsEncryptCertificatesLivePath/$selectedDomainName/privkey
 [admin]
 addr = \"0.0.0.0:8881\"
 " > "$defaultUrsaProxyConfigPath" || exit 1
-fi
 
   echo "✅ Updated the config.toml by including the [server] settings"
   echo
@@ -423,7 +425,7 @@ fi
   echo
 
   # Ursa server configuration handler to ensure the settings exist and correct
-  ursaServerConfigurationHandler 1
+  ursaServerConfigurationHandler
 
   echo "🤖 Ursa proxy"
 
@@ -573,7 +575,12 @@ fi
   echo
 
   echo "🤖 Set Ursa proxy configuration for SSL/TLS"
-  ursaServerConfigurationHandler 2
+  if ! curl -X POST 0.0.0.0:8881/reload-tls-config; then
+    echo "💩 Uh oh! Failed to reload the ursa-proxy TLS configuration."
+    echo
+
+    sleep 3
+  fi
 
   echo
 
