refactor: 💡 TIAS on latest ursa proxy amends

diff --git a/scripts/install_docker b/scripts/install_docker
--- a/scripts/install_docker
+++ b/scripts/install_docker
@@ -35,7 +35,7 @@
 # - Do a health check to confirm the Fleek Network Node is running
 #
 # Contributing?
-# - If you'd like to test changes locally use the env var `USE_BRANCH_NAME_FOR_GH_RAW`, for remote locales pulls
+# - If you'd like to test changes locally use the env var `USE_BRANCH_NAME_FOR_GH_RAW` and `URSA_BRANCH`, for remote locales pulls
 #
 # Found an issue? Please report it here: https://github.com/fleek-network/get.fleek.network
 
@@ -72,6 +72,7 @@ defaultUrsaProxyDir="$defaultUrsaBasePath/proxy"
 defaultUrsaProxyConfigPath="$defaultUrsaProxyDir/config.toml"
 defaultLetsEncryptCertificatesLivePath="/etc/letsencrypt/live"
 defaultDockerNetworkUrsaHostname="full-node-ursa-1"
+defaultDockerNetworkUrsaProxyHostname="full-node-ursa-proxy-1"
 
 # App state
 userSelectedLanguage=""
@@ -432,6 +433,14 @@ dockerComposeExec() {
     sudo docker compose "$@"
   else
     sudo docker-compose "$@"
+  fi
+}
+
+yqExec() {
+  if yq --version >/dev/null 2>&1; then
+    sudo yq "$@"
+  else
+    sudo /snap/bin/yq "$@"
   fi
 }
 
@@ -1201,11 +1210,8 @@ echo "# Server without TLS.
 proxy_pass = \"$defaultDockerNetworkUrsaHostname:4069\"
 listen_addr = \"0.0.0.0:80\"
 serve_dir_path = \".well-known\"
-" | sudo tee "$defaultUrsaProxyConfigPath" || exit 1
-elif [[ $1 -eq "2" ]]; then
-# Here "no identation" is intentional, do not change
-# The top empty line at the top is intentional
-echo "# Server with TLS
+
+# Server with TLS
 [[server]]
 proxy_pass = \"$defaultDockerNetworkUrsaHostname:4069\"
 listen_addr = \"0.0.0.0:443\"
@@ -1219,6 +1225,24 @@ key_path = \"$defaultLetsEncryptCertificatesLivePath/$userDomainName/privkey.pem
 [admin]
 addr = \"0.0.0.0:8881\"
 " | sudo tee "$defaultUrsaProxyConfigPath" || exit 1
+elif [[ $1 -eq "2" ]]; then
+# # Here "no identation" is intentional, do not change
+# # The top empty line at the top is intentional
+# echo "# Server with TLS
+# [[server]]
+# proxy_pass = \"$defaultDockerNetworkUrsaHostname:4069\"
+# listen_addr = \"0.0.0.0:443\"
+
+# [server.tls]
+# cert_path = \"$defaultLetsEncryptCertificatesLivePath/$userDomainName/fullchain.pem\"
+# key_path = \"$defaultLetsEncryptCertificatesLivePath/$userDomainName/privkey.pem\"
+
+# # Admin service.
+# # You can omit this section as this is the default.
+# [admin]
+# addr = \"0.0.0.0:8881\"
+# " | sudo tee "$defaultUrsaProxyConfigPath" || exit 1
+  echo "[debug] replace by endpoint call"
 fi
   # TODO: Create translation
   echo "✅ Updated the config.toml by including the [server] settings"
@@ -1375,7 +1399,7 @@ verifyDepsOrInstall() {
         showOkMessage "${transl[verify_deps_installed_via_package_manager]/_name_/$name} snap"
 
         # ensure snap is in the PATH and pkgs
-        PATH="$PATH:/snap/bin"
+        export PATH="$PATH:/snap/bin"
 
         return 0
       fi
@@ -1557,7 +1581,18 @@ setupSSLTLS() {
 
   # TODO: Create translation
   echo "🤖 Set Ursa proxy configuration for SSL/TLS"
-  ursaServerConfigurationHandler 2
+  # ursaServerConfigurationHandler 2
+  if ! dockerComposeExec -f "$defaultDockerComposeYmlRelativePath" run \
+    --rm --entrypoint "\
+    if ! curl -X POST 0.0.0.0:8881/reload-tls-config; then
+      exit 1;
+    fi
+    " "$defaultDockerNetworkUrsaProxyHostname"; then
+    echo "💩 Uh oh! Failed to reload the ursa-proxy TLS configuration."
+    echo
+
+    sleep 3
+  fi
 
   if [[ ! -f "$defaultUrsaProxyConfigPath" ]]; then
     # TODO: Create translation
@@ -1610,10 +1645,10 @@ onLatestPreference() {
 
       break
     elif [[ "$data" -eq 0 ]]; then
-      sudo yq -ie 'del(.services.ursa.build)' "$defaultDockerComposeYmlRelativePath" >/dev/null 2>&1
-      sudo yq -i ".services.ursa.image = \"$defaultUrsaLatestImage\"" "$defaultDockerComposeYmlRelativePath" >/dev/null 2>&1
+      yqExec -ie 'del(.services.ursa.build)' "$defaultDockerComposeYmlRelativePath" >/dev/null 2>&1
+      yqExec -i ".services.ursa.image = \"$defaultUrsaLatestImage\"" "$defaultDockerComposeYmlRelativePath" >/dev/null 2>&1
 
-      if ! sudo yq '.services.ursa.image' "$defaultDockerComposeYmlRelativePath" | grep -q "$defaultUrsaLatestImage" || ! sudo yq '.services.ursa.build' "$defaultDockerComposeYmlRelativePath" | grep -qE "null|no matches found"; then
+      if ! yqExec '.services.ursa.image' "$defaultDockerComposeYmlRelativePath" | grep -q "$defaultUrsaLatestImage" || ! yqExec '.services.ursa.build' "$defaultDockerComposeYmlRelativePath" | grep -qE "null|no matches found"; then
         echo
         echo "💩 ${transl[on_latest_preference_uh_oh_failed_modify_docker_compose_yaml]}"
 
