refactor: 💡 ursa-proxy as a systemd service (#20)

diff --git a/scripts/lets_encrypt b/scripts/lets_encrypt
--- a/scripts/lets_encrypt
+++ b/scripts/lets_encrypt
@@ -42,125 +42,93 @@ if [[ "$hasPortsAvailable" -eq 1 ]]; then
   exit 1
 fi
 
-(
-  exec < /dev/tty;
+# Confirm validators
+confirmDomainName() {
+  local validate="^([a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]\.)+[a-zA-Z]{2,}$"
 
-  # Defaults
-  defaultUrsaPath="$HOME/fleek-network/ursa"
-  defaultUrsaConfigFilename="config.toml"
-  defaultUrsaBasePath="$HOME/.ursa"
-  defaultUrsaConfigPath="$defaultUrsaBasePath/$defaultUrsaConfigFilename"
-  defaultUrsaProxyDir="$defaultUrsaBasePath/proxy"
-  defaultUrsaProxyConfigPath="$defaultUrsaProxyDir/config.toml"
-  defaultLetsEncryptCertificatesLivePath="/etc/letsencrypt/live"
+  if ! hasCommand whois; then
+    sudo DEBIAN_FRONTEND=noninteractive apt-get install whois -yq
+  fi
 
-  # User data
-  selectedDomainName=""
-  selectedEmailAddress=""
-  selectedIpAddress=""
-  selectedUrsaPath=""
+  if whois "$1" | grep -Ei '[Uu]nallocated|returned 0 objects' > /dev/null; then
+    return 1
+  fi
 
-  # Confirm validators
-  confirmDomainName() {
-    local validate="^([a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]\.)+[a-zA-Z]{2,}$"
+  [[ $1 =~ $validate ]]
+}
 
-    if ! hasCommand whois; then
-      sudo DEBIAN_FRONTEND=noninteractive apt-get install whois -yq
-    fi
+confirmEmailAddress() {
+  local validate="^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]+$"
 
-    if whois "$1" | grep -Ei '[Uu]nallocated|returned 0 objects' > /dev/null; then
-      return 1
-    fi
+  [[ "$1" =~ $validate ]]
+}
 
-    [[ $1 =~ $validate ]]
-  }
+validateIpAddress() {
+  local validate="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$"
 
-  confirmEmailAddress() {
-    local validate="^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]+$"
+  [[ "$1" =~ $validate ]] && ping -c1 -W1 "$1" > /dev/null
+}
 
-    [[ "$1" =~ $validate ]]
-  }
+getIpAddress() {
+  detectedIpAddress=$(curl -s ifconfig.me)
 
-  validateIpAddress() {
-    local validate="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$"
+  if validateIpAddress "$detectedIpAddress"; then
+    echo "$detectedIpAddress"
 
-    [[ "$1" =~ $validate ]] && ping -c1 -W1 "$1" > /dev/null
-  }
+    return
+  fi
 
-  getIpAddress() {
-    detectedIpAddress=$(curl -s ifconfig.me)
+  detectedIpAddress=$(curl -s icanhazip.com)
 
-    if validateIpAddress "$detectedIpAddress"; then
-      echo "$detectedIpAddress"
+  if validateIpAddress "$detectedIpAddress"; then
+    echo "$detectedIpAddress"
 
-      return
-    fi
+    return
+  fi
 
-    detectedIpAddress=$(curl -s icanhazip.com)
+  detectedIpAddress=$(curl -s ident.me)
 
-    if validateIpAddress "$detectedIpAddress"; then
-      echo "$detectedIpAddress"
+  if validateIpAddress "$detectedIpAddress"; then
+    echo "$detectedIpAddress"
 
-      return
-    fi
+    return
+  fi
 
-    detectedIpAddress=$(curl -s ident.me)
+  echo "ERROR_IP_ADDRESS_NOT_AVAILABLE"
+}
 
-    if validateIpAddress "$detectedIpAddress"; then
-      echo "$detectedIpAddress"
+domainNameConfSettingsVerificationHandler() {
+  domainCertPath=$(grep -i "cert_path" "$defaultUrsaProxyConfigPath" | cut -d '/' -f 5)
+  domainKeyPaty=$(grep -i "key_path" "$defaultUrsaProxyConfigPath" | cut -d '/' -f 5)
 
-      return
-    fi
+  if [[ ! "$domainCertPath" == "$domainKeyPaty" ]]; then
+    echo "🤷‍♀️ Unexpected settings in the Ursa configuration file, the domain name in server.tls cert_path and key_path should be equal. Make the necessary changes and save the file before retrying..."
+    echo
 
-    echo "ERROR_IP_ADDRESS_NOT_AVAILABLE"
-  }
+    exit 1
+  fi
 
-  domainNameConfSettingsVerificationHandler() {
-    domainCertPath=$(grep -i "cert_path" "$defaultUrsaConfigPath" | cut -d '/' -f 5)
-    domainKeyPaty=$(grep -i "key_path" "$defaultUrsaConfigPath" | cut -d '/' -f 5)
+  if [[ "$domainCertPath" == "$selectedDomainName" ]]; then
+    echo "✅ The Ursa configuration file has server settings and user provided domain name matches the settings"
+    echo
 
-    if [[ ! "$domainCertPath" == "$domainKeyPaty" ]]; then
-      echo "🤷‍♀️ Unexpected settings in the Ursa configuration file, the domain name in server.tls cert_path and key_path should be equal. Make the necessary changes and save the file before retrying..."
-      echo
+    return 0
+  fi
+
+  while read -rp "🙋‍♀️ The Ursa configuration for server has the domain set as $domainCertPath. By proceeding the configuration settings will be reset and lost, is this ok? (yes/no) " answer; do
+    if [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
+      rm "$defaultUrsaProxyConfigPath"
+
+      break;
+    elif [[ $answer == [nN] || $answer == [nN][oO] ]]; then
+      echo "🦖 The Let's Encrypt process has terminated, due to existing configuration file and settings that you have decided to keep."
 
       exit 1
     fi
+  done  
+}
 
-    if [[ "$domainCertPath" == "$selectedDomainName" ]]; then
-      echo "✅ The Ursa configuration file has server settings and user provided domain name matches the settings"
-      echo
-
-      return 0
-    fi
-
-    while read -rp "🙋‍♀️ The Ursa configuration for server has the domain set as $domainCertPath. Is this correct? (yes/no) " answer; do
-      if [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
-        break;
-      elif [[ $answer == [nN] || $answer == [nN][oO] ]]; then
-        while read -rp "🙋‍♀️ We'll update the configuration domain to $selectedDomainName. Is this ok? Type \"no\" to change (yes/no) " answer; do
-          if [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
-            break;
-          elif [[ $answer == [nN] || $answer == [nN][oO] ]]; then
-            read -rp "🙋‍♀️ What's the domain name" answer
-            selectedDomainName="$answer"
-            break;
-          fi
-        done
-
-        if ! sed -i "s|$domainCertPath|$selectedDomainName|" "$defaultUrsaProxyConfigPath"; then
-          echo "👹 Oh no! Failed to update the domain name in the config.toml, make the changes manually before retrying."
-          echo
-
-          exit 1
-        fi
-
-        echo "✅ Updated the config.toml by replacing the domain name to $selectedDomainName"
-        echo
-      fi
-    done
-  }
-
-  ursaServerConfigurationHandler() {
+ursaServerConfigurationHandler() {
   if [[ ! -d "$defaultUrsaProxyDir" ]]; then
     echo "✅ Create Ursa proxy directory"
     mkdir -p "$defaultUrsaProxyDir"
@@ -185,8 +153,7 @@ fi
 
 # Here "no identation" is intentional, do not change
 # The top empty line at the top is intentional
-echo "
-# Server without TLS.
+echo "# Server without TLS.
 [[server]]
 proxy_pass = \"127.0.0.1:4069\"
 listen_addr = \"0.0.0.0:80\"
@@ -195,8 +162,7 @@ serve_dir_path = \".well-known\"
 elif [[ $1 -eq "2" ]]; then
 # Here "no identation" is intentional, do not change
 # The top empty line at the top is intentional
-echo "
-# Server with TLS
+echo "# Server with TLS
 [[server]]
 proxy_pass = \"127.0.0.1:4069\"
 listen_addr = \"0.0.0.0:443\"
@@ -214,11 +180,60 @@ fi
 
   echo "✅ Updated the config.toml by including the [server] settings"
   echo
-  }
+}
 
-  hasCommand() {
-    command -v "$1" >/dev/null 2>&1
-  }
+hasCommand() {
+  command -v "$1" >/dev/null 2>&1
+}
+
+runHealthCheckForHTTPS() {
+  printf "🚑 Health check %s via HTTPS /ping endpoint\n" "$selectedDomainName"
+  if ! curl -s https://$selectedDomainName/ping | grep -q pong; then
+    printf "💩 Uh-oh! Failed to health-check the domain %s\n" "$selectedDomainName"
+  else
+    printf "✅ Health check was successful!\n"
+  fi
+}
+
+(
+  exec < /dev/tty;
+
+  # Defaults
+  defaultUrsaPath="$HOME/fleek-network/ursa"
+  defaultUrsaConfigFilename="config.toml"
+  defaultUrsaBasePath="$HOME/.ursa"
+  defaultUrsaConfigPath="$defaultUrsaBasePath/$defaultUrsaConfigFilename"
+  defaultUrsaProxyDir="$defaultUrsaBasePath/proxy"
+  defaultUrsaProxyConfigPath="$defaultUrsaProxyDir/config.toml"
+  defaultLetsEncryptCertificatesLivePath="/etc/letsencrypt/live"
+
+  # User data
+  selectedDomainName=""
+  selectedEmailAddress=""
+  selectedIpAddress=""
+  selectedUrsaPath=""
+
+  if ! curl -s localhost:4069/ping | grep -q pong; then
+    echo "💩 Uh oh! The ursa network node should be running."
+
+    if systemctl list-units --full -all | grep -q "ursa.service"; then
+      while read -rp "🙋‍♀️ The ursa service is available. Would you like to start it now? (yes/no) "; do
+        if [[ $answer == [nN] || $answer == [nN][oO] ]]; then
+          echo "🦖 The Let's Encrypt setup has terminated. Make sure to have the ursa network node running before retrying..."
+
+          exit 1
+        elif [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
+          if ! sudo systemctl start ursa; then
+            echo "👹 Oops! Failed to start the ursa service"
+
+            exit 1
+          fi
+        fi
+      done
+    else
+      exit 1
+    fi
+  fi
 
   while read -rp "🙋‍♀️ Is the Ursa repository source-code in the default path $defaultUrsaPath? Type \"no\" to change the location (yes/no) " answer; do
     if [[ $answer == [nN] || $answer == [nN][oO] ]]; then
@@ -305,16 +320,36 @@ fi
 
     while read -rp "🙋‍♀️ Would you like to renew the certificates? (yes/no) " answer; do
       if [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
-        if ! sudo certbot renew; then
+
+        echo "🤖 Stop the ursa-proxy to free port 80"
+        if ! sudo systemctl stop ursa-proxy; then
+          echo "👹 Oops! Failed to stop the ursa-proxy that is required to allow the certbot to renew the certificates"
+
+          exit 1
+        fi
+
+        if ! certbot certonly \
+          --standalone \
+          --cert-name "$selectedDomainName"; then
           echo "👹 Oops! Failed to renew the certificates for some reason"
 
           exit 1
         fi
+
         echo "✅ The certficates were renewed!"
+
+        echo "🤖 Restart the ursa-proxy"
+        if ! sudo systemctl restart ursa-proxy; then
+          echo "👹 Oops! Failed to restart the ursa-proxy"
+
+          exit 1
+        fi
+
+        runHealthCheckForHTTPS
 
         exit 0
       elif [[ $answer == [nN] || $answer == [nN][oO] ]]; then
-        echo "💩 Oh no! Backup your certificates and clear the directory to retry and run this process"
+        echo "🦖 The Let's Encrypt process has terminated."
         echo
 
         exit 1
@@ -344,50 +379,37 @@ fi
   ursaServerConfigurationHandler 1
 
   echo "🤖 Ursa proxy"
-  ursaProxyPID=$(pidof ursa-proxy | tr ' ' '\n')
 
-  if [[ ! "$ursaProxyPID" ]]; then
-    if hasCommand ursa-proxy; then
-      while read -rp "🙋‍♀️ We found ursa-proxy. Would you like to start it now? (yes/no)" answer; do
-        if [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
-          if ! sudo systemctl restart ursa-proxy; then
-            printf "👹 Oops! Failed to start the ursa-proxy systemd service\n"
+  if systemctl list-units --full -all | grep -q "ursa-proxy.service"; then
+    echo "✅ The Ursa-proxy service is available"
+    echo
 
-            exit 1
-          fi
+    if systemctl is-active --quiet ursa-proxy; then
+      echo "🦖 We'll stop the ursa-proxy for a bit, for certbot standalone web server"
+      sudo systemctl stop ursa-proxy
+    fi
+  else
+    while read -rp "🙋‍♀️ The ursa-proxy service was not found. Would you like to have it installed now? (yes/no) " answer; do
+      if [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
+        read -rp "💡 The ursa-proxy service installer is a separate process that will be executed, when complete, the Let's Encrypt setup will continue. Press ENTER to continue..."
 
-          ursaProxyPID=$(pidof ursa-proxy | tr ' ' '\n')
-          break;
-        elif [[ $answer == [nN] || $answer == [nN][oO] ]]; then
-          echo "🦖 The Lets Encrypt setup was interrupted because the ursa-proxy has not started. Make sure that you start the ursa-proxy before you retry..."
+        if ! curl -s https://get.fleek.network/install_ursa_proxy | bash; then
+          echo "👹 Oh no! Failed to install the ursa-proxy"
 
           exit 1
         fi
-      done
-    else
-      printf "👹 Oops! The ursa-proxy process has to be running. Make sure that you start the ursa-proxy before you retry...\n"
 
-      exit 1
-    fi
+        echo "🦖 We'll stop the ursa-proxy for now. The certbot standalone web server will launch for the certification process shortly"
+        sudo systemctl stop ursa-proxy
+
+        break;
+      elif [[ $answer == [nN] || $answer == [nN][oO] ]]; then
+        echo "🦖 The Lets Encrypt setup was interrupted because the ursa-proxy is not installed. Make sure that you install, setup the ursa-proxy before retrying..."
+
+        exit 1
+      fi
+    done
   fi
-
-  printf "🚑 Ursa proxy health-check\n"
-  pingAttempts=0
-  while ! curl -s localhost/ping | grep -q pong; do
-    if [[ "$pingAttempts" -gt 10 ]]; then
-      echo "👹 Oh no! Failed to health-check the ursa proxy"
-      echo
-
-      break;
-    fi
-
-    printf "🤖 Awaiting for Ursa proxy on port 80, attempt number %s...\n" "$pingAttempts"
-    sleep 1
-
-    ((pingAttempts++))
-  done
-
-  echo
 
   echo "🤖 Certbot"
   if ! hasCommand whois; then
@@ -402,7 +424,6 @@ fi
   if ! sudo certbot certonly \
     --standalone \
     --preferred-challenges http \
-    --webroot -w "$selectedUrsaPath" \
     --email "$selectedEmailAddress" \
     --domain "$selectedDomainName" \
     --rsa-key-size 4096 \
@@ -412,12 +433,39 @@ fi
     echo "💡 If you already had Certbot installed, make sure you update to latest before retrying please"
 
     exit 1
+  else
+    echo "✅ Certbot process completed"
   fi
 
   if [[ -d "$selectedUrsaPath/.well-known" ]]; then
     echo "💩 Uh oh! The temporary directory $selectedUrsaPath/.well-known should've been removed. Feel free to delete it!"
     echo
   fi
+
+  echo
+
+  echo "🤖 The ursa-proxy service is now going to restart"
+  if ! sudo systemctl restart ursa-proxy; then
+    printf "👹 Oops! Failed to restart the ursa-proxy systemd service\n"
+
+    exit 1
+  fi
+
+  printf "🚑 Ursa proxy health-check\n"
+  pingAttempts=0
+  while ! curl -s "localhost:4069/ping" | grep -q pong; do
+    if [[ "$pingAttempts" -gt 10 ]]; then
+      echo "👹 Oh no! Failed to health-check the ursa proxy"
+      echo
+
+      exit 1
+    fi
+
+    printf "🤖 Awaiting for Ursa proxy on port 80, attempt number %s...\n" "$pingAttempts"
+    sleep 1
+
+    ((pingAttempts++))
+  done
 
   printf "🤖 Set Ursa server IP Address in the configuration file\n"
   if [[ -f "$defaultUrsaConfigPath" ]]; then
@@ -455,7 +503,35 @@ fi
 
   echo
 
+  if [[ ! -d $defaultLetsEncryptCertificatesLivePath/$selectedDomainName ]]; then
+    echo "💩 Uh no! You have some cleaning to do because we've failed to find the $selectedDomainName certificates directory"
+    echo
+    echo "To prevent name clashing, Let's Encrypt uses the naming convention $selectedDomainName-000x for domains that were previously certified. If that's the case, you can have this fixed by following the suggested commands."
+    echo
+    echo "Check the list of certificates:"
+    echo "sudo certbot certificates"
+    echo
+    echo "Delete a certificate:"
+    echo "sudo certbot delete --cert-name example.com"
+    echo
+    echo "✨ Once ready, run this script again."
+
+    exit 1
+  fi
+
+  echo
+
   echo "✅ The certification is now complete!"
   echo "The ursa-proxy configuration was updated, including the SSL/TLS certifications, etc."
-  echo "Restart the ursa-proxy manually for the TLS configuration to take effect, please!"
+  echo
+  echo "🤖 The ursa-proxy service is now going to restart"
+  if ! sudo systemctl restart ursa-proxy; then
+    printf "👹 Oops! Failed to restart the ursa-proxy systemd service\n"
+
+    exit 1
+  fi
+
+  echo
+
+  runHealthCheckForHTTPS
 )
