chore: 🤖 workdir handling

diff --git a/scripts/lets_encrypt b/scripts/lets_encrypt
--- a/scripts/lets_encrypt
+++ b/scripts/lets_encrypt
@@ -28,6 +28,7 @@
 dateRuntime=$(date '+%Y%m%d%H%M%S')
 
 # Defaults
+defaultUrsaPath="$HOME/fleek-network/ursa"
 defaultUrsaConfigFilename="config.toml"
 defaultUrsaBasePath="$HOME/.ursa"
 defaultUrsaConfigPath="$defaultUrsaBasePath/$defaultUrsaConfigFilename"
@@ -41,6 +42,7 @@ declare -a requiredPorts=(80 443 4069 6009)
 selectedDomainName=""
 selectedEmailAddress=""
 selectedIpAddress=""
+selectedUrsaPath=""
 
 getIpAddress() {
   detectedIpAddress=$(curl -s ifconfig.me)
@@ -187,6 +189,32 @@ hasCommand() {
 
 if ! hasCommand ursa-proxy; then
   echo "💩 Oh no! The ursa-proxy was not found in the system PATH. Make sure you install it correctly before retrying."
+  echo
+
+  exit 1
+fi
+
+while read -rp "🙋‍♀️ Is the Ursa repository source-code in the default path $defaultUrsaConfigPath? Type \"no\" to change the location (yes/no)"; do
+  if [[ $answer == [nN] || $answer == [nN][oO] ]]; then
+    while read -rp "🙋‍♀️ What's the location where the Ursa repository is?" answer; do
+      if [[ -d "$answer" ]]; then
+        selectedUrsaPath="$answer"
+        
+        break
+      fi
+
+      echo "💩 Uh oh! The path ($answer) doesn't exist, let's try that again..."
+    done
+  elif [[ $answer == [yY] || $answer == [yY][eE][sS] ]]; then
+    selectedUrsaPath="$defaultUrsaPath"
+
+    break;
+  fi
+done
+
+echo "🤖 Change work directory to $selectedUrsaPath"
+if ! cd "$selectedUrsaPath"; then
+  echo "👹 Oops! Failed to change work directory to \"$selectedUrsaPath\" for some reason..."
   echo
 
   exit 1
