chore: 🤖 update script, systemd service unit handling

diff --git a/scripts/update b/scripts/update
--- a/scripts/update
+++ b/scripts/update
@@ -13,6 +13,8 @@ defaultLightningDiagnosticLogAbsPath="$defaultLightningLogPath/$defaultLightning
 defaultLightningOutputLogAbsPath="$defaultLightningLogPath/$defaultLightningOutputFilename"
 defaultLightningLogPath="/var/log/$defaultName"
 defaultTargetName="release"
+defaultLightningSystemdServiceName="$defaultName"
+defaultLightningSystemdServicePath="/etc/systemd/system/$defaultLightningSystemdServiceName.service"
 
 (
   exec < /dev/tty;
@@ -89,6 +91,13 @@ defaultTargetName="release"
     printf "👹 Oops! Failed to symlink %s to /usr/local/bin/$defaultCLIAlias\n" "$defaultLightningPath/target/$defaultTargetName/$defaultCLIBuildName"
     echo
     read -rp "😅 After the installation, if $defaultName $defaultCLIBuildName CLI command is unavailable globally, then you need to add $defaultLightningPath/target/$defaultTargetName/$defaultCLIBuildName to your system PATH or symlink the binary to /usr/local/bin/$defaultCLIAlias, as we've failed to do it. Press ENTER to continue..."
+  fi
+
+  echo "🤖 Update the systemd service $defaultName.service"
+  if ! sudo sed -i "s/^ExecStart=.*/ExecStart=$defaultCLIAlias run/g" "$defaultLightningSystemdServicePath"; then
+    echo "👹 Oops! Failed to find and replace the property name ExecStart in $defaultLightningSystemdServicePath. You're advised to check our reference document to help troubleshoot https://docs.fleek.network/references/Lightning%20CLI/error-linking-with-cc-failed-exist-status-1/"
+
+    exit 1
   fi
 
   echo "🌈 The update has now completed."
