refactor: 💡 update build as install with lock core/cli

diff --git a/scripts/update b/scripts/update
--- a/scripts/update
+++ b/scripts/update
@@ -144,7 +144,7 @@ defaultTempLogFilePath="/var/tmp"
   fi
 
   printf "🤖 Build and install the %s CLI\n" "$defaultName"
-  if ! cargo +stable build --release; then
+  if ! cargo +stable install --locked --path core/cli; then
     printf "👹 Oops! Failed to build and install the %s CLI. If you are experiencing issues, help us improve by letting us know in our Discord %s\n" "$defaultName" "$defaultDiscordUrl"
 
     exit 1
@@ -156,10 +156,12 @@ defaultTempLogFilePath="/var/tmp"
     fi
   fi
 
-  if ! sudo ln -s "$defaultLightningPath/target/$defaultTargetName/$defaultCLIBuildName" /usr/local/bin/$defaultCLIAlias; then
-    printf "👹 Oops! Failed to symlink %s to /usr/local/bin/$defaultCLIAlias\n" "$defaultLightningPath/target/$defaultTargetName/$defaultCLIBuildName"
-    echo
-    read -rp "😅 After the installation, if $defaultName $defaultCLIBuildName CLI command is unavailable globally, then you need to add $defaultLightningPath/target/$defaultTargetName/$defaultCLIBuildName to your system PATH or symlink the binary to /usr/local/bin/$defaultCLIAlias, as we've failed to do it. Press ENTER to continue..."
+  if [[ -f "$HOME/.cargo/bin/$defaultName" ]]; then
+    if ! sudo ln -s "$HOME/.cargo/bin/$defaultName" /usr/local/bin/$defaultCLIAlias; then
+      printf "👹 Oops! Failed to symlink %s to /usr/local/bin/%s\n" "$HOME/.cargo/bin/$defaultName" "$defaultName"
+      echo
+      read -rp "😅 After the installation, if $defaultName CLI command is not available globally, then you need to add $HOME/.cargo/bin/lightning to your system PATH or symlink the binary to /usr/local/bin/$defaultName, as we've failed to do it. Press ENTER to continue..."
+    fi
   fi
 
   echo "🚑 Verify $defaultLightningConfigPath..."
